# builder enviroment
# FROM alpine:3.4 AS builder
FROM sirius1242/bam:alpine3.4 AS builder
WORKDIR /src
COPY . .
# speed up apk downloading (for China mainland)
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk update && apk upgrade
RUN apk add --no-cache openssl gcc g++ make cmake python bam icu-dev libmaxminddb-dev
RUN bam server_release nogeolocation=true

# production enviroment (alpine
FROM alpine:3.4 AS production
WORKDIR /infclassr_srv/
RUN apk update && apk upgrade
COPY --from=builder /src/bin/server .
COPY --from=builder /src/autoexec.cfg .
COPY --from=builder /src/bin/data data
COPY --from=builder /usr/lib/libgcc_s.so.1 /usr/lib/libstdc++.so.6 /usr/lib/libicui18n.so.57 /usr/lib/libicuuc.so.57 /usr/lib/libicudata.so.57 /usr/lib/libmaxminddb.so.0 /usr/lib/
EXPOSE 8303/udp
ENTRYPOINT ["./server"]
